### ISSUE TITLE
exception, why?

### ISSUE THREAD

**Issue by gushenghua** [studio-ousia/mprpc#27]
File "mprpc/client.pyx", line 226, in mprpc.client.RPCPoolClient.call (mprpc/client.c:3635)
    return RPCClient.call(self, method, *args)
  File "mprpc/client.pyx", line 137, in mprpc.client.RPCClient.call (mprpc/client.c:2489)
    return self._parse_response(response)
  File "mprpc/client.pyx", line 155, in mprpc.client.RPCClient._parse_response (mprpc/client.c:2808)
    raise RPCError('Invalid Message ID')
RPCError: Invalid Message ID

**Comment by pykler** [comment]
I had this error using the client inside a multiprocessing.pool.ThreadPool ... switched to use gevent.pool.Group worked for me. My guess is because I was using the gevent Connection Pool to connect to the server.

**Comment by hendrik-cliqz** [comment]
Are you somehow sharing the client? This happens if a socket is not cleanly created for every worker. 

E.g. if you are using multiprocessing and initialize the Client before processes are forked the socket - which is nothing else than a file handle - is copied as well. So it basically means multiple codepaths talk to the RPCServer via the same network connection.
